# Generated by Django 4.1.5 on 2023-01-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
